apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: veeva-sre
  labels:
    app: backend-app
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
      tier: backend
  template:
    metadata:
      labels:
        app: backend-app
        tier: backend
    spec:
      containers:
      - name: tomcat
        image: 244249005753.dkr.ecr.eu-west-2.amazonaws.com/veeva-sre-cluster-backend:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: CATALINA_OPTS
          value: "-Xmx512m -Xms256m"
        - name: ENVIRONMENT
          value: "dev"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: logs
          mountPath: /usr/local/tomcat/logs
      volumes:
      - name: logs
        emptyDir: {}
      restartPolicy: Always 